version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: tackle
    container_name: dgi-docker
    # init: true
    # privileged: true
    volumes:
      - ..:/app
    command: "sleep infinity"
    environment:
      FLASK_APP: service:app
      NEO4J_BOLT_URL: "neo4j://neo4j:konveyor@neo4j:7687"
      GRAPH_FACTS_DIR: /app/doop-data/output
    networks:
      - dev
    depends_on:
      - neo4j

  # Neo4J UI URL: http://localhost:7474/browser/
  neo4j:
    image: neo4j:4.4.17
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: konveyor
      NEO4J_AUTH: neo4j/konveyor
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_dbms_security_procedures_whitelist: gds.*, apoc.*
      NEO4J_dbms_security_procedures_unrestricted: gds.*, apoc.*
    volumes:
      - neo4j:/data
    networks:
      - dev

volumes:
  neo4j:

networks:
  dev: null
