name: CI Build
on:
  push:
    branches:
      - main
    paths-ignore:
    - '**.md'
    - docs/

  pull_request:
    branches:
      - main
    paths-ignore:
    - '**.md'
    - docs/

jobs:
  build:
    runs-on: ubuntu-latest
    # use a known build environment
    container: python:3.9-slim

    # Required services
    services:
      neo4j:
        image: neo4j:4.4.17
        env:
          NEO4J_USERNAME: neo4j
          NEO4J_PASSWORD: konveyor
          NEO4J_AUTH: neo4j/konveyor      
        ports:
          - 7474:7474
          - 7687:7687

    # Steps for the build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -e .[dev]

      - name: Linting
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 dgi --count --select=E9,F63,F7,F82 --show-source --statistics
          # The GitHub editor is 127 chars wide
          flake8 dgi --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: nosetests
        env:
          TERM: xterm-256color
          NEO4J_BOLT_URL: "neo4j://neo4j:konveyor@neo4j:7687"

      # - name: Upload code coverage
      #   uses: codecov/codecov-action@v2 
      #   with:
      #     version: "v0.1.13"